#%RAML 0.8
title: myapi
mediaType: application/json
baseUri: /

/base:
  get:
  /{id}:
    get:
      description: Get base entity by ID
      responses:
        200:
          body:
            application/json:
              schema: NamedResponseType
schemas:
  - NamedResponseType: |
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "id": "http://jsonschema.net",
        "required": true
      }