#%RAML 0.8
title: raml2springmvc_invalid_raml_response_statuscode_missing
version: "0.0.1"
baseUri: /api
/customers: 
  get:
    responses:
      description: Example.
      body:
        text/plain:
