#%RAML 0.8
title: API
baseUri: /
version: 1.0

/users:
    post:
      body:
        application/json:
          schema: |
                  {
                    "type" : "object"
                  }
    put:
      body:
        application/json:
          schema: |
                  {
                    "type" : "object"
                  }
