#%RAML 1.0

title: Samp API
version: v0.1
baseUri: sample_unit
mediaType:  application/json

types:
  responseType:
    type: object
    additionalProperties: false
    description: "Facebook auth for the user"
    properties:
      privileges:
        displayName: Privileges
        type: object
        description: "privileges for the user"
        required: true
        properties:
          contentPrivileges:
            enum: [ PREMIUM_BLOCKED, PREMIUM_GRANTED]
          adsPrivileges:
            enum: [  NO_ADS, SHOW_ADS]

/sample_units:
  displayName: Samples
  description: A collection of samples
  post:
    description: Creates a sample unit
    body:
#      properties:
#        a:
#          type: string
#        b:
#          type: integer
    responses:
      201:
        body:
          type: responseType
          description: The sample unit has been successfully created.