#%RAML 0.8
title: myapi
baseUri: /
version: 1

/base:
  /endpointWithGet:
    get:
  /endpointWithGetAndPost:   
/secondBase:
  /endpointWithGet:    
    get:
  /endpointWithURIParam:
    /{uriParam}:
      get:
      post:
