#%RAML 1.0
title: myapi
baseUri: /
version: 1

types:
  TestType: 
    type: object
    properties: 
      id: integer
      name: string

/base:
  /services:
    /things:
      get:
        responses: 
          200:
            body: 
              application/json:
                type: TestType
                  