#%RAML 0.8
title: myapi
baseUri: /
version: 1

/base:
  /endpointWithGetAndPost:
    put:
      body:
        application/json:
          schema: |
                  {
                    "type" : "object",
                    "properties" : {
                      "stuffId" : {
                        "type" : "integer"
                      },
                      "coolerId" : {
                        "type" : "integer"
                      }
                    }
                  }
      responses:
        200:
          body:
            application/json:
              schema: |
                      {
                        "type" : "object",
                        "properties" : {
                          "stuffId" : {
                            "type" : "integer"
                          },
                          "coolerId" : {
                            "type" : "integer"
                          }
                        }
                      }
    post:
      body:
        application/json:
          schema: |
                  {
                    "type" : "object",
                    "properties" : {
                      "stuffId" : {
                        "type" : "integer"
                      },
                      "coolerId" : {
                        "type" : "integer"
                      }
                    }
                  }
      responses:
        200:
          body:           
            application/json:
              schema: |
                      {
                        "type" : "object",
                        "properties" : {
                          "stuffId" : {
                            "type" : "integer"
                          },
                          "coolerId" : {
                            "type" : "integer"
                          }
                        }
                      }
    delete:
    get:
  /endpointThatWillBoom:
    put:
    post:
    delete:
