package com.phoenixnap.oss.ramlapisync.generation.rules.basic;

import com.phoenixnap.oss.ramlapisync.data.ApiMappingMetadata;
import com.phoenixnap.oss.ramlapisync.generation.rules.Rule;
import com.sun.codemodel.JMethod;

/**
 * Generates an empty method body returning null and a TODO comment.
 *
 * INPUT:
 * #%RAML 0.8
 * title: myapi
 * mediaType: application/json
 * baseUri: /
 * /base:
 *   /{id}
 *     get:
 *
 * OUTPUT:
 * return null; //TODO Autogenerated Method Stub. Implement me please.
 *
 * The name of the field can be configured. Default is "delegate".
 *
 * @author armin.weisser
 * @since 0.3.2
 */
public class ImplementMeMethodBodyRule implements Rule<JMethod, JMethod, ApiMappingMetadata> {

    @Override
    public JMethod apply(ApiMappingMetadata endpointMetadata, JMethod generatableType) {
        generatableType.body().directStatement("return null; //TODO Autogenerated Method Stub. Implement me please.");
        return generatableType;
    }
}
