package com.phoenixnap.oss.ramlapisync.generation.rules;

import java.util.Map;

/**
 * An Extension of the rule interface to represent rules that are configurable
 *
 * @param <T>
 *            The type of the source code item on which this rule can operate. E.g. JClass.
 * @param <R>
 *            The type of the source code item generated by this rule. E.g. JMethod.
 * @param <M>
 *            The type of the meta data that this rule should operate on. E.g ApiControllerMetadata.
 *
 * @author kurt.paris
 * @since 0.5.0
 */
public interface ConfigurableRule<T, R, M> extends Rule<T, R, M> {
	
	/**
	 * Accepts a key-value representation of the the configurations and their respective values
	 * 
	 * @param configuration The Map with the configuration to applye
	 */
	void applyConfiguration(Map<String, String> configuration);

}
