package com.phoenixnap.oss.ramlapisync.generation.rules;

import com.phoenixnap.oss.ramlapisync.data.ApiControllerMetadata;

/**
 * Represents a RAML Schema rule (production from RAML Schema). Can be executed
 * or 'applied' to perform the code generation steps associated with that schema
 * rule.
 *
 * @param <T>
 *            The type of source code item on which this rule can operate
 * @param <R>
 *            The type of the source code item generated by this rule
 *
 * @author armin.weisser
 */
public interface ControllerRule<T, R> {

    /**
     * Add whatever Java source is required to the given generatable to
     * represent this schema rule.
     *
     * @param controllerMetadata
     *            the JSON schema node that has caused this rule to be applied
     * @param generatableType
     *            A code generation construct to which this rule should be
     *            applied
     * @return the newly generated source code item that was added/created as a
     *         result of executing this rule
     */
    R apply(ApiControllerMetadata controllerMetadata, T generatableType);

}
