package com.phoenixnap.oss.ramlapisync.generation.rules;

import com.phoenixnap.oss.ramlapisync.data.ApiMappingMetadata;
import com.sun.codemodel.JMethod;

/**
 * @author armin.weisser
 * @since 0.3.2
 */
public class ImplementMeMethodBodyRule implements Rule<JMethod, JMethod, ApiMappingMetadata> {

    @Override
    public JMethod apply(ApiMappingMetadata endpointMetadata, JMethod generatableType) {
        generatableType.body().directStatement("return null; //TODO Autogenerated Method Stub. Implement me please.");
        return generatableType;
    }
}
