package com.phoenixnap.oss.ramlapisync.generation.rules;

/**
 * Represents a RAML2Code Generation rule (production from RAML Schema). Can be executed
 * or 'applied' to perform the code generation steps associated with that schema
 * rule.
 *
 * @param <T>
 *            The type of source code item on which this rule can operate
 * @param <R>
 *            The type of the source code item generated by this rule
 * @param <M>
 *            The type of the meta data that this rule should operate on
 *
 * @author armin.weisser
 */
public interface Rule<T, R, M> {

    /**
     * Add whatever Java source is required to the given generatable to
     * represent this schema rule.
     *
     * @param metadata
     *            the meta data that has caused this rule to be applied
     * @param generatableType
     *            A code generation construct to which this rule should be
     *            applied
     * @return the newly generated source code item that was added/created as a
     *         result of executing this rule
     */
    R apply(M metadata, T generatableType);

}
