package com.phoenixnap.oss.ramlapisync.generation.rules;

import com.phoenixnap.oss.ramlapisync.data.ApiMappingMetadata;
import com.sun.codemodel.JDefinedClass;
import com.sun.codemodel.JMethod;

/**
 * @author armin.weisser
 * @since 0.3.2
 */
public class Spring4ControllerMethodStubRule implements Rule<JDefinedClass, JMethod, ApiMappingMetadata> {

    private Rule<JDefinedClass, JMethod, ApiMappingMetadata> methodSignatureRule = new Spring4ControllerMethodSignatureRule();

    @Override
    public JMethod apply(ApiMappingMetadata endpointMetadata, JDefinedClass generatableType) {
        JMethod jMethod = methodSignatureRule.apply(endpointMetadata, generatableType);
        jMethod.body().directStatement("return null; //TODO Autogenerated Method Stub. Implement me please.");
        return jMethod;
    }
}
