#%RAML 1.0
title: Test

types:
  Data:
    type: object
    properties:
      name:
        type: string
      dateOnly: date-only
      timeOnly: time-only
      datetimeOnly: datetime-only
      datetimeNoFormat: 
        type: datetime
      datetimeRFC3339: 
        type: datetime
        format: rfc3339
      datetimeRFC2616: 
        type: datetime
        format: rfc2616

/test:
  get:
    responses:
      200:
        body:
          application/json:
            type: Data