#%RAML 1.0
title: API
version: 1.0

types:
  User:
    properties:
      firstName: 
        type: string
        minLength: 5
        maxLength: 50
      lastName: 
        type: string
        pattern: "^[a-z]+$"
      nickName?: string

/users:
  post:
    body: 
      application/json:
        type: User
  get:
    responses:
      200:
        body:
          application/json:
            type: User[]