#%RAML 0.8
title: myapi
baseUri: /
version: 1

/base:
  get:
    queryParameters:
      queryParam1:
        type: integer
      queryParam2:
        type: string
  /endpointWithGetAndPost:
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status" : "UP"
                }
    post:
/secondBase:
  get:
  /endpointWithGet:    
    get:
  /endpointWithURIParam:
    /{uriParam}:
      get:
