#%RAML 1.0
title: myapi
documentation:
  - title: Home
    content: |
      Welcome to the _Sample API_ Documentation.
  - title: Legal
    content: |
      CWIE (c) All Rights Reserved
baseUri: api
mediaType: application/json
types:
  Person:
    type: object
  Manager:
    type: Person

/persons:
/managers: