#%RAML 1.0
title: myapi
baseUri: api
mediaType: application/json
types:
  Person:
    type: object
  Manager:
    type: Person

/persons:
  displayName: Persons handling
  get:
    displayName: GetPersons
    description: Get all persons
    responses: 
      200:
        description: Successful response
        body: 
          application/json:
            schema: Person
/managers: